const fs = require("fs");
const globby = require("globby");
const path = require("path");
const _ = require("lodash");

(async () => {
  const readmePaths = await globby(path.resolve(__dirname, "../../packages/*/README.md"));
  const packageJsonPaths = readmePaths.map((readmePath) =>
    readmePath.replace("README.md", "package.json")
  );

  const packages = await Promise.all(
    readmePaths.map(async (readmePath, i) => {
      const readme = await fs.promises.readFile(readmePath, "utf-8");
      const packageJsonPath = packageJsonPaths[i];
      const pkg = JSON.parse(await fs.promises.readFile(packageJsonPath, "utf-8"));
      const name = pkg.name.replace("@uplift-ltd/", "");
      const filename = _.kebabCase(name);

      await fs.promises.writeFile(
        path.resolve(__dirname, `../docs/packages/${filename}.md`),
        `---\ntitle: ${name}\n---\n\n` + readme.split("\n").slice(2).join("\n")
      );

      return {
        name,
        filename,
      };
    })
  );

  const sidebars = {
    sidebar: {
      "Getting Started": ["getting-started/installation", "getting-started/contributing"],
      Packages: packages.map(({ filename }) => `packages/${filename}`),
    },
  };

  await fs.promises.writeFile(
    path.resolve(__dirname, "../sidebars.js"),
    [
      "// This file is generated by scripts/update-docs.js",
      `module.exports = ${JSON.stringify(sidebars, null, 2)}`,
    ].join("\n")
  );
})();
