import {
  GRAPHQL_TOKEN,
  GRAPHQL_HOST,
  GRAPHQL_BATCHING,
  GRAPHQL_AUTH_ENDPOINT,
  GRAPHQL_UNAUTH_ENDPOINT,
  IS_SSR,
  IS_REACT_NATIVE,
} from "@uplift-ltd/constants";

export const GRAPHQL_AUTH_URL =
  IS_SSR || IS_REACT_NATIVE ? `${GRAPHQL_HOST}${GRAPHQL_AUTH_ENDPOINT}` : GRAPHQL_AUTH_ENDPOINT;

export const GRAPHQL_UNAUTH_URL =
  IS_SSR || IS_REACT_NATIVE ? `${GRAPHQL_HOST}${GRAPHQL_UNAUTH_ENDPOINT}` : GRAPHQL_UNAUTH_ENDPOINT;

export {
  GRAPHQL_TOKEN,
  GRAPHQL_HOST,
  GRAPHQL_BATCHING,
  GRAPHQL_AUTH_ENDPOINT,
  GRAPHQL_UNAUTH_ENDPOINT,
};
