import {
  GRAPHQL_TOKEN,
  GRAPHQL_HOST,
  GRAPHQL_BATCHING,
  GRAPHQL_AUTH_ENDPOINT,
  GRAPHQL_UNAUTH_ENDPOINT,
  GRAPHQL_AUTH_URL,
  GRAPHQL_UNAUTH_URL,
} from "@uplift-ltd/constants";

export {
  GRAPHQL_TOKEN,
  GRAPHQL_HOST,
  GRAPHQL_BATCHING,
  GRAPHQL_AUTH_ENDPOINT,
  GRAPHQL_UNAUTH_ENDPOINT,
  GRAPHQL_AUTH_URL,
  GRAPHQL_UNAUTH_URL,
};
