// This file is generated by scripts/update-docs.js
module.exports = {
  sidebar: {
    "Getting Started": ["getting-started/installation", "getting-started/contributing"],
    Packages: [
      "packages/apollo",
      "packages/constants",
      "packages/create-nexus-package",
      "packages/formik",
      "packages/graphene",
      "packages/money",
      "packages/push-notifications",
      "packages/react-native-debug",
      "packages/react-native-updates",
      "packages/sass",
      "packages/react-native-screen-views",
      "packages/scripts",
      "packages/sentry",
      "packages/setup-proxy",
      "packages/strings",
      "packages/ts-helpers",
      "packages/use-after-delay",
      "packages/use-keyboard-visible",
      "packages/use-on-page-scroll",
      "packages/use-safe-timeout",
    ],
  },
};
