name: "combine dependabot prs"

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  combine:
    runs-on: ubuntu-latest
    steps:
      - name: GHA-combine-PRs
        uses: vic1707/GHA-combine-PRs@1.0.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}