name: publish preview

on:
  pull_request:
    branches: [master]

jobs:
  publish-preview:
    if: github.event.pull_request.merged != true && github.event.pull_request.closed != true
    environment:
      name: Preview
      url: "https://${{ steps.create-preview-url.outputs.preview_url}}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js with GitHub Packages
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
          registry-url: "https://npm.pkg.github.com/"
          scope: "@uplift-ltd"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore dependencies
        uses: actions/cache@main
        env:
          cache-name: npm-cache
        with:
          path: |
            node_modules
            packages/*/node_modules
          key:
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}-${{
            hashFiles('packages/*/package.json') }}

      - name: Install dependencies
        run:
          yarn install --non-interactive --frozen-lockfile --cache-folder ${{
          steps.yarn-cache-dir-path.outputs.dir }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: Create Preview URL
        id: create-preview-url
        run: |
          echo "::set-output name=preview_url::nexus-$GITHUB_REF_NAME_SLUG_URL.surge.sh"

      - name: Publish to surge
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
        run: |
          cd ./website
          yarn build
          yarn surge ./build ${{ steps.create-preview-url.outputs.preview_url }}
